### PR TITLE
goodbye

### PR DESCRIPTION
**Pull request by MorphTuple**

### CODE REVIEW

**Comment by zsotroav** [comment]
Are you sure about this?

**Comment by MorphTuple** [comment]
> 
> 
> Are you sure about this?

Yes

**Review by zsotroav — APPROVED** [review]
> Yes

Thank you for your help. Goodbye.

**Comment by MorphTuple** [comment]
> 
> 
> > Yes
> 
> Thank you for your help. Goodbye.

@Yuuto-Project/developers 
I'm getting more busy and busier each day.
Thank you for the collab, it was nice while it lasted. Hopefully you guys can find new people to work on the project.

**Pull request merged**
